#!/bin/bash

STACK_NAME="mystackname"
TEMPLATE="packaged.yml"
PARAMETERS_FILE="parameters.json"
PARAMS=($(jq -r '.Parameters[] | [.ParameterKey, .ParameterValue] | "\(.[0])=\(.[1])"' ${PARAMETERS_FILE}))
BUCKET_NAME="mybucketname"

mvn clean package && \
aws cloudformation package     --template-file template.yml     --output-template-file packaged.yml     --s3-bucket $BUCKET_NAME && \


aws cloudformation deploy \
	    --template-file "${TEMPLATE}" \
	        --stack-name "${STACK_NAME}" \
		    --parameter-overrides ${PARAMS[@]} \
		    --capabilities CAPABILITY_IAM