#!/bin/bash
STACK_NAME="carl-stack-09-09"
TEMPLATE="packaged.yml"
PARAMETERS_FILE="parameters.json"
PARAMS=($(jq -r '.Parameters[] | [.ParameterKey, .ParameterValue] | "\(.[0])=\(.[1])"' ${PARAMETERS_FILE}))
aws cloudformation deploy \
        --template-file "${TEMPLATE}" \
            --stack-name "${STACK_NAME}" \
            --parameter-overrides ${PARAMS[@]} \
            --capabilities CAPABILITY_IAM
