AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Parameters:
  TableName:
    Type: String
    Default: sam-bookings-api-dev-elin
Globals:
  Function:
    Timeout: 20
    MemorySize: 1024
    Environment:
      Variables:
        BOOKINGS_TABLE_NAME:
          Ref: TableName
Resources:
  GetBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-elin-bucket/6ddf8530445b47acae632aa9e0ce93b3
      Handler: com.wirelessiths.handler.GetBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: TableName
      Events:
        GetBooking:
          Type: Api
          Properties:
            Path: /bookings/{id}
            Method: get
  ListBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-elin-bucket/6ddf8530445b47acae632aa9e0ce93b3
      Handler: com.wirelessiths.handler.ListBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: TableName
      Events:
        GetBookings:
          Type: Api
          Properties:
            Path: /bookings
            Method: get
  ListBookingsByUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-elin-bucket/6ddf8530445b47acae632aa9e0ce93b3
      Handler: com.wirelessiths.handler.ListBookingsByUserHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: TableName
      Events:
        GetBooking:
          Type: Api
          Properties:
            Path: /bookings-by-user
            Method: get
  DeleteBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-elin-bucket/6ddf8530445b47acae632aa9e0ce93b3
      Handler: com.wirelessiths.handler.DeleteBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      Events:
        DeleteBooking:
          Type: Api
          Properties:
            Path: /bookings/{id}
            Method: delete
  CreateBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-elin-bucket/6ddf8530445b47acae632aa9e0ce93b3
      Handler: com.wirelessiths.handler.CreateBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      Events:
        CreateBooking:
          Type: Api
          Properties:
            Path: /bookings
            Method: post
  UpdateBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-elin-bucket/6ddf8530445b47acae632aa9e0ce93b3
      Handler: com.wirelessiths.UpdateBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      Events:
        UpdateBooking:
          Type: Api
          Properties:
            Path: /bookings/{id}
            Method: put
  BookingsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: sam-bookings-api-dev
      AttributeDefinitions:
      - AttributeName: bookingId
        AttributeType: S
      - AttributeName: startTime
        AttributeType: S
      - AttributeName: endTime
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
      KeySchema:
      - AttributeName: bookingId
        KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: timeIndex
        KeySchema:
        - AttributeName: startTime
          KeyType: HASH
        - AttributeName: endTime
          KeyType: RANGE
        Projection:
          ProjectionType: KEYS_ONLY
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: userIndex
        KeySchema:
        - AttributeName: userId
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
Outputs:
  GetBookingFunction:
    Description: GetBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetBookingFunction
      - Arn
  ListBookingFunction:
    Description: ListBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ListBookingFunction
      - Arn
  ListBookingsByUserFunction:
    Description: ListBookingsByUser Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ListBookingsByUserFunction
      - Arn
  DeleteBookingFunction:
    Description: DeleteBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - DeleteBookingFunction
      - Arn
  CreateBookingFunction:
    Description: CreateBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateBookingFunction
      - Arn
  UpdateBookingFunction:
    Description: UpdateBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - UpdateBookingFunction
      - Arn
