AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Parameters:
  TableName:
    Type: String
    Default: bookings-api-dev-adam-09-04
  CodeUri:
    Type: String
    Default: target/bookings-api-dev.jar
  UserPoolArn:
    Type: String
    Default: xxx
  UserPoolId:
    Type: String
    Default: xxx
Globals:
  Function:
    Timeout: 20
    MemorySize: 1024
    Environment:
      Variables:
        BOOKINGS_TABLE_NAME:
          Ref: TableName
        USER_POOL_ID:
          Ref: UserPoolId
Resources:
  GetBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-bookings-adam/a50cb9aac8caca4705e8b0757953fdc1
      Handler: com.wirelessiths.handler.GetBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: TableName
      Events:
        GetBooking:
          Type: Api
          Properties:
            Path: /bookings/{id}
            Method: get
  ListBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-bookings-adam/a50cb9aac8caca4705e8b0757953fdc1
      Handler: com.wirelessiths.handler.ListBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: TableName
      Events:
        GetBookings:
          Type: Api
          Properties:
            Path: /bookings
            Method: get
  ListBookingsByUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-bookings-adam/a50cb9aac8caca4705e8b0757953fdc1
      Handler: com.wirelessiths.handler.ListBookingsByUserHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: TableName
      Events:
        GetBooking:
          Type: Api
          Properties:
            Path: /bookings-by-user
            Method: get
  DeleteBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-bookings-adam/a50cb9aac8caca4705e8b0757953fdc1
      Handler: com.wirelessiths.handler.DeleteBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      Events:
        DeleteBooking:
          Type: Api
          Properties:
            Path: /bookings/{id}
            Method: delete
  CreateBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-bookings-adam/a50cb9aac8caca4705e8b0757953fdc1
      Handler: com.wirelessiths.handler.CreateBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      Events:
        CreateBooking:
          Type: Api
          Properties:
            Path: /bookings
            Method: post
  UpdateBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-bookings-adam/a50cb9aac8caca4705e8b0757953fdc1
      Handler: com.wirelessiths.UpdateBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      Events:
        UpdateBooking:
          Type: Api
          Properties:
            Path: /bookings/{id}
            Method: put
  ReturnScooterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-bookings-adam/a50cb9aac8caca4705e8b0757953fdc1
      Handler: com.wirelessiths.handler.ReturnScooterHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      Events:
        UpdateForReturnScooterBooking:
          Type: Api
          Properties:
            Path: /bookings/return/{id}
            Method: put
  GetUserInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-bookings-adam/a50cb9aac8caca4705e8b0757953fdc1
      Handler: com.wirelessiths.handler.GetUserInfoHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      - Statement:
          Effect: Allow
          Action:
          - cognito-idp:AdminGetUser
          - cognito-idp:ListUsers
          Resource:
            Ref: UserPoolArn
      Events:
        GetUserInfo:
          Type: Api
          Properties:
            Path: /bookings/getuserinfo
            Method: GET
  BookingsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Ref: TableName
      AttributeDefinitions:
      - AttributeName: scooterId
        AttributeType: S
      - AttributeName: endTime
        AttributeType: S
      - AttributeName: bookingId
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      - AttributeName: startTime
        AttributeType: S
      KeySchema:
      - AttributeName: scooterId
        KeyType: HASH
      - AttributeName: endTime
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: userIndex
        KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: startTime
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: bookingIndex
        KeySchema:
        - AttributeName: bookingId
          KeyType: HASH
        - AttributeName: startTime
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: dateIndex
        KeySchema:
        - AttributeName: date
          KeyType: HASH
        - AttributeName: scooterId
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
Outputs:
  GetBookingFunction:
    Description: GetBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetBookingFunction
      - Arn
  ListBookingFunction:
    Description: ListBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ListBookingFunction
      - Arn
  ListBookingsByUserFunction:
    Description: ListBookingsByUser Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ListBookingsByUserFunction
      - Arn
  DeleteBookingFunction:
    Description: DeleteBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - DeleteBookingFunction
      - Arn
  CreateBookingFunction:
    Description: CreateBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateBookingFunction
      - Arn
  UpdateBookingFunction:
    Description: UpdateBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - UpdateBookingFunction
      - Arn
  ReturnScooterFunction:
    Description: ReturnScooter Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ReturnScooterFunction
      - Arn
  GetUserInfoFunction:
    Description: GetUserInfo Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetUserInfoFunction
      - Arn
