AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Parameters:
  UserPoolId:
    Type: String
    Default: xxx
  UserPoolArn:
    Type: String
    Default: xxx
  TableName:
    Type: String
    Default: carl-bookings
  CodeUri:
    Type: String
    Default: target/bookings-api-dev.jar
  CognitoUserPoolName:
    Type: String
    Default: MyUserPool
  CognitoUserPoolClientName:
    Type: String
    Default: MyUserPoolClient
Globals:
  Function:
    Timeout: 20
    MemorySize: 1024
    Environment:
      Variables:
        BOOKINGS_TABLE_NAME:
          Ref: TableName
        USER_POOL_ID:
          Ref: UserPoolId
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors: '''*'''
      Auth:
        ApiKeyRequired: false
        DefaultAuthorizer: MyCognitoAuth
        Authorizers:
          MyCognitoAuth:
            UserPoolArn:
              Ref: UserPoolArn
            Identity:
              Header: Authorization
  GetBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://carl-bucket-29/cd792ba8797ed535d01f5d40335a493b
      Handler: com.wirelessiths.handler.GetBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: TableName
      Events:
        GetBooking:
          Type: Api
          Properties:
            Path: /bookings/{id}
            Method: get
            RestApiId:
              Ref: MyApi
  ListBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://carl-bucket-29/cd792ba8797ed535d01f5d40335a493b
      Handler: com.wirelessiths.handler.ListBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: TableName
      Events:
        GetBookings:
          Type: Api
          Properties:
            Path: /bookings
            Method: get
            RestApiId:
              Ref: MyApi
  ListBookingsByUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://carl-bucket-29/cd792ba8797ed535d01f5d40335a493b
      Handler: com.wirelessiths.handler.ListBookingsByUserHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: TableName
      Events:
        GetBooking:
          Type: Api
          Properties:
            Path: /users/{id}/bookings
            Method: get
            RestApiId:
              Ref: MyApi
  BookingStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://carl-bucket-29/cd792ba8797ed535d01f5d40335a493b
      Handler: com.wirelessiths.handler.SetBookingStatusHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: TableName
      Events:
        GetBooking:
          Type: Api
          Properties:
            Path: /bookings/{id}/status
            Method: get
            RestApiId:
              Ref: MyApi
  DeleteBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://carl-bucket-29/cd792ba8797ed535d01f5d40335a493b
      Handler: com.wirelessiths.handler.DeleteBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      Events:
        DeleteBooking:
          Type: Api
          Properties:
            Path: /bookings/{id}
            Method: delete
            RestApiId:
              Ref: MyApi
  CreateBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://carl-bucket-29/cd792ba8797ed535d01f5d40335a493b
      Handler: com.wirelessiths.handler.CreateBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      Events:
        CreateBooking:
          Type: Api
          Properties:
            Path: /bookings
            Method: post
            RestApiId:
              Ref: MyApi
  UpdateBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://carl-bucket-29/cd792ba8797ed535d01f5d40335a493b
      Handler: com.wirelessiths.handler.UpdateBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      Events:
        UpdateBooking:
          Type: Api
          Properties:
            Path: /bookings/{id}
            Method: put
            RestApiId:
              Ref: MyApi
  ActivateBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://carl-bucket-29/cd792ba8797ed535d01f5d40335a493b
      Handler: com.wirelessiths.handler.ActivateBookingHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      Events:
        ActivateBooking:
          Type: Api
          Properties:
            Path: /bookings/activate
            Method: post
            RestApiId:
              Ref: MyApi
  ReturnScooterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://carl-bucket-29/cd792ba8797ed535d01f5d40335a493b
      Handler: com.wirelessiths.handler.ReturnScooterHandler::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      - Statement:
          Effect: Allow
          Action:
          - cognito-idp:AdminGetUser
          - cognito-idp:ListUsers
          Resource:
            Ref: UserPoolArn
      Events:
        UpdateForReturnScooterBooking:
          Type: Api
          Properties:
            Path: /bookings/return
            Method: put
            RestApiId:
              Ref: MyApi
  BookingsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Ref: TableName
      AttributeDefinitions:
      - AttributeName: scooterId
        AttributeType: S
      - AttributeName: endTime
        AttributeType: S
      - AttributeName: bookingId
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      - AttributeName: startTime
        AttributeType: S
      KeySchema:
      - AttributeName: scooterId
        KeyType: HASH
      - AttributeName: endTime
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: userIndex
        KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: startTime
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: bookingIndex
        KeySchema:
        - AttributeName: bookingId
          KeyType: HASH
        - AttributeName: startTime
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: dateIndex
        KeySchema:
        - AttributeName: date
          KeyType: HASH
        - AttributeName: scooterId
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
Outputs:
  GetBookingFunction:
    Description: GetBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetBookingFunction
      - Arn
  ListBookingFunction:
    Description: ListBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ListBookingFunction
      - Arn
  ListBookingsByUserFunction:
    Description: ListBookingsByUser Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ListBookingsByUserFunction
      - Arn
  DeleteBookingFunction:
    Description: DeleteBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - DeleteBookingFunction
      - Arn
  CreateBookingFunction:
    Description: CreateBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateBookingFunction
      - Arn
  UpdateBookingFunction:
    Description: UpdateBooking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - UpdateBookingFunction
      - Arn
  ActivateBookingFunction:
    Description: Activate Booking Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ActivateBookingFunction
      - Arn
  ReturnScooterFunction:
    Description: ReturnScooter Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ReturnScooterFunction
      - Arn
