AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM template for Serverless framework service: '

Globals:
  Function:
    Timeout: 20
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        BOOKINGS_TABLE_NAME: sam-bookings-api-dev

Resources:
  BookingsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: sam-bookings-api-dev
      AttributeDefinitions:
        - AttributeName: bookingId
          AttributeType: S
        - AttributeName: startTime
          AttributeType: S
        - AttributeName: endTime
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: bookingId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: timeIndex
          KeySchema:
            - AttributeName: startTime
              KeyType: HASH
            - AttributeName: endTime
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: userIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  BookingsApiListBookings:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.wirelessiths.ListBookingHandler
      Runtime: java8
      CodeUri: target/bookings-api-adam-dev.jar
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:Query'
                - 'dynamodb:Scan'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:DeleteItem'
              Resource:
                - 'Fn::GetAtt':
                    - BookingsDynamoDBTable
                    - Arn
                - 'Fn::Join':
                    - /
                    - - 'Fn::GetAtt':
                          - BookingsDynamoDBTable
                          - Arn
                      - index/*
      Events:
        Event1:
          Type: Api
          Properties:
            Path: /bookings
            Method: get
            RestApiId:
              Ref: BookingsApi
  BookingsApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: '2.0'
        info:
          title:
            Ref: 'AWS::StackName'
        paths:
          /bookings:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BookingsApiListBookings.Arn}/invocations
              responses: {}
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BookingsApiCreateBooking.Arn}/invocations
              responses: {}
          /bookings-by-user:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BookingsApiListBookingsByUser.Arn}/invocations
              responses: {}
          '/bookings/{id}':
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BookingsApiGetBooking.Arn}/invocations
              responses: {}
            delete:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BookingsApiDeleteBooking.Arn}/invocations
              responses: {}
  BookingsApiListBookingsLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - "BookingsApiListBookings"
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: "BookingsApiListBookings"
      Principal: apigateway.amazonaws.com
  BookingsApiListBookingsByUser:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.wirelessiths.ListBookingsByUserHandler
      Runtime: java8
      CodeUri: target/bookings-api-adam-dev.jar
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:Query'
                - 'dynamodb:Scan'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:DeleteItem'
              Resource:
                - 'Fn::GetAtt':
                    - BookingsDynamoDBTable
                    - Arn
                - 'Fn::Join':
                    - /
                    - - 'Fn::GetAtt':
                          - BookingsDynamoDBTable
                          - Arn
                      - index/*
      Events:
        Event1:
          Type: Api
          Properties:
            Path: /bookings-by-user
            Method: get
            RestApiId:
              Ref: BookingsApi
  BookingsApiListBookingsByUserLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - BookingsApiListBookingsByUser
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: BookingsApiListBookingsByUser
      Principal: apigateway.amazonaws.com
  BookingsApiGetBooking:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.wirelessiths.GetBookingHandler
      Runtime: java8
      CodeUri: target/bookings-api-adam-dev.jar
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:Query'
                - 'dynamodb:Scan'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:DeleteItem'
              Resource:
                - 'Fn::GetAtt':
                    - BookingsDynamoDBTable
                    - Arn
                - 'Fn::Join':
                    - /
                    - - 'Fn::GetAtt':
                          - BookingsDynamoDBTable
                          - Arn
                      - index/*
      Events:
        Event1:
          Type: Api
          Properties:
            Path: '/bookings/{id}'
            Method: get
            RestApiId:
              Ref: BookingsApi
  BookingsApiGetBookingLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - "BookingsApiGetBooking"
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: "BookingsApiGetBooking"
      Principal: apigateway.amazonaws.com
  BookingsApiCreateBooking:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.wirelessiths.CreateBookingHandler
      Runtime: java8
      CodeUri: target/bookings-api-adam-dev.jar
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:Query'
                - 'dynamodb:Scan'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:DeleteItem'
              Resource:
                - 'Fn::GetAtt':
                    - BookingsDynamoDBTable
                    - Arn
                - 'Fn::Join':
                    - /
                    - - 'Fn::GetAtt':
                          - BookingsDynamoDBTable
                          - Arn
                      - index/*
      Events:
        Event1:
          Type: Api
          Properties:
            Path: /bookings
            Method: post
            RestApiId:
              Ref: BookingsApi
  BookingsApiCreateBookingLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - BookingsApiCreateBooking
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: BookingsApiCreateBooking
      Principal: apigateway.amazonaws.com
  BookingsApiDeleteBooking:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.wirelessiths.DeleteBookingHandler
      Runtime: java8
      CodeUri: target/bookings-api-adam-dev.jar
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:Query'
                - 'dynamodb:Scan'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:DeleteItem'
              Resource:
                - 'Fn::GetAtt':
                    - BookingsDynamoDBTable
                    - Arn
                - 'Fn::Join':
                    - /
                    - - 'Fn::GetAtt':
                          - BookingsDynamoDBTable
                          - Arn
                      - index/*
      Events:
        Event1:
          Type: Api
          Properties:
            Path: '/bookings/{id}'
            Method: delete
            RestApiId:
              Ref: BookingsApi
  BookingsApiDeleteBookingLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - BookingsApiDeleteBooking
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: BookingsApiDeleteBooking
      Principal: apigateway.amazonaws.com
