AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
Parameters:
  UserPoolId:
    Type: String
    Default: xxx
  UserPoolArn:
    Type: String
    Default: xxx
  TableName:
    Type: String
    Default: xxx
  BucketName:
    Type: String
    Default: xxx
  CodeUri:
    Type: String
    Default: target/bookings-api-dev.jar
  CognitoUserPoolName:
    Type: String
    Default: MyUserPool
  CognitoUserPoolClientName:
    Type: String
    Default: MyUserPoolClient
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        BOOKINGS_TABLE_NAME: !Ref TableName
        USER_POOL_ID: !Ref UserPoolId

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        ApiKeyRequired: false # OPTIONAL
        DefaultAuthorizer: MyCognitoAuth # OPTIONAL, if you use IAM permissions, specify AWS_IAM.
          # For AWS_IAM:
        # DefaultAuthorizer: AWS_IAM
        # InvokeRole: NONE # CALLER_CREDENTIALS by default unless overridden
        Authorizers:
          MyCognitoAuth:
            UserPoolArn: !Ref UserPoolArn
            # Can also accept an array
            Identity: # OPTIONAL
              Header: Authorization # OPTIONAL; Default: 'Authorization'

  GetBookingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.GetBookingHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableName
      Events:
        GetBooking:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bookings/{id}
            Method: get
            RestApiId: !Ref MyApi  # Add this line
  ListBookingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.ListBookingHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableName
      Events:
        GetBookings:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bookings
            Method: get
            RestApiId: !Ref MyApi  # Add this line
  ListBookingsByUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.ListBookingsByUserHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableName
      Events:
        GetBooking:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users/{id}/bookings
            Method: get
            RestApiId: !Ref MyApi  # Add this line
  BookingStatusFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.SetBookingStatusHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableName
      Events:
        GetBooking:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bookings/{id}/status
            Method: get
            RestApiId: !Ref MyApi  # Add this line
  DeleteBookingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.DeleteBookingHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        DeleteBooking:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bookings/{id}
            Method: delete
            RestApiId: !Ref MyApi  # Add this line
  CreateBookingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.CreateBookingHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
        - S3ReadPolicy:
            BucketName: !Ref BucketName
      Events:
        CreateBooking:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bookings
            Method: post
            RestApiId: !Ref MyApi  # Add this line
  UpdateBookingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.UpdateBookingHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        UpdateBooking:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bookings/{id}
            Method: put
            RestApiId: !Ref MyApi  # Add this line

  BookingsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: scooterId
          AttributeType: S
        - AttributeName: endTime
          AttributeType: S
        - AttributeName: bookingId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: startTime
          AttributeType: S
      KeySchema:
        - AttributeName: scooterId
          KeyType: HASH
        - AttributeName: endTime
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: userIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: startTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: bookingIndex
          KeySchema:
            - AttributeName: bookingId
              KeyType: HASH
            - AttributeName: startTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: dateIndex
          KeySchema:
            - AttributeName: date
              KeyType: HASH
            - AttributeName: scooterId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

Outputs:
  GetBookingFunction:
    Description: "GetBooking Lambda Function ARN"
    Value: !GetAtt GetBookingFunction.Arn

  ListBookingFunction:
    Description: "ListBooking Lambda Function ARN"
    Value: !GetAtt ListBookingFunction.Arn

  ListBookingsByUserFunction:
    Description: "ListBookingsByUser Lambda Function ARN"
    Value: !GetAtt ListBookingsByUserFunction.Arn

  DeleteBookingFunction:
    Description: "DeleteBooking Lambda Function ARN"
    Value: !GetAtt DeleteBookingFunction.Arn

  CreateBookingFunction:
    Description: "CreateBooking Lambda Function ARN"
    Value: !GetAtt CreateBookingFunction.Arn

  UpdateBookingFunction:
    Description: "UpdateBooking Lambda Function ARN"
    Value: !GetAtt UpdateBookingFunction.Arn

