AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
Parameters:
  TableName:
    Type: String
    Default: bookings-api-dev-carl
  CodeUri:
    Type: String
    Default: target/bookings-api-dev.jar
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        BOOKINGS_TABLE_NAME: !Ref TableName

Resources:
  GetBookingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.GetBookingHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableName
      Events:
        GetBooking:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bookings/{id}
            Method: get
  ListBookingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.ListBookingHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableName
      Events:
        GetBookings:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bookings
            Method: get
  ListBookingsByUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.ListBookingsByUserHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableName
      Events:
        GetBooking:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bookings-by-user
            Method: get
  DeleteBookingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.DeleteBookingHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        DeleteBooking:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bookings/{id}
            Method: delete
  CreateBookingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.CreateBookingHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        CreateBooking:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bookings
            Method: post
  UpdateBookingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.UpdateBookingHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        UpdateBooking:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bookings/{id}
            Method: put
  ActivateBookingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.ActivateBookingHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        ActivateBooking:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bookings/activate
            Method: post
  ReturnBookingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/bookings-api-dev.jar
      Handler: com.wirelessiths.handler.ReturnBookingHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        UpdateForReturnScooterBooking:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bookings/return/{id}
            Method: put
  BookingsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
      - AttributeName: scooterId
        AttributeType: S
      - AttributeName: endTime
        AttributeType: S
      - AttributeName: bookingId
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      - AttributeName: startTime
        AttributeType: S
      KeySchema:
      - AttributeName: scooterId
        KeyType: HASH
      - AttributeName: endTime
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: userIndex
        KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: startTime
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: bookingIndex
        KeySchema:
        - AttributeName: bookingId
          KeyType: HASH
        - AttributeName: startTime
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: dateIndex
        KeySchema:
        - AttributeName: date
          KeyType: HASH
        - AttributeName: scooterId
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

Outputs:
  GetBookingFunction:
    Description: "GetBooking Lambda Function ARN"
    Value: !GetAtt GetBookingFunction.Arn

  ListBookingFunction:
    Description: "ListBooking Lambda Function ARN"
    Value: !GetAtt ListBookingFunction.Arn

  ListBookingsByUserFunction:
    Description: "ListBookingsByUser Lambda Function ARN"
    Value: !GetAtt ListBookingsByUserFunction.Arn

  DeleteBookingFunction:
    Description: "DeleteBooking Lambda Function ARN"
    Value: !GetAtt DeleteBookingFunction.Arn

  CreateBookingFunction:
    Description: "CreateBooking Lambda Function ARN"
    Value: !GetAtt CreateBookingFunction.Arn

  UpdateBookingFunction:
    Description: "UpdateBooking Lambda Function ARN"
    Value: !GetAtt UpdateBookingFunction.Arn

  ActivateBookingFunction:
    Description: "Activate Booking Lambda Function ARN"
    Value: !GetAtt ActivateBookingFunction.Arn



